- hosts: all
  roles:
    - common
    - flannel

- hosts: vbox
  roles:
    - dns

- hosts: masters
  become: yes
  roles:
    - registry
    - etcd
    - certs
    - kube-master

- hosts: nodes
  become: yes
  roles:
    - kubelet
